docs: fix path to logo
aws-ia/taskcat pull request #688
Opened 2021-09-21 06:04 UTC by GlennChia

## Overview

Change path to `taskcat.svg` to render svg logo

## Testing/Steps taken to ensure quality

Manual verification of README in branch

2021-09-24 22:03 UTC, GlennChia commented
@tonynv, I noticed you just made a fresh PR for something similar. There are 2 READMEs that have the old broken logo link. I've modified my PR to use the link that you used in your PR for both READMEs. Requesting your review for this. Thanks!

2021-09-24 22:49 UTC, andrew-glenn submitted a review, later dismissed

2021-11-04 20:26 UTC, tonynv commented on README.md
> +[![logo](https://raw.githubusercontent.com/aws-quickstart/taskcat/main/assets/docs/images/tcat.png)](https://taskcat.io/)
```suggestion
[![logo](https://raw.githubusercontent.com/aws-ia/taskcat/main/assets/docs/images/tcat.png)](https://taskcat.io/)
```

2021-11-04 20:26 UTC, tonynv commented on docs/README.md
> +[![logo](https://raw.githubusercontent.com/aws-quickstart/taskcat/main/assets/docs/images/tcat.png)](https://taskcat.io/)
```suggestion
[![logo](https://raw.githubusercontent.com/aws-ia/taskcat/main/assets/docs/images/tcat.png)](https://taskcat.io/)
```

2021-11-04 20:28 UTC, tonynv requested changes

2021-11-04 20:28 UTC, tonynv commented on docs/README.md
> +[![logo](https://raw.githubusercontent.com/aws-quickstart/taskcat/main/assets/docs/images/tcat.png)](https://taskcat.io/)
We have migrated taskcat to the aws-ia org.  Some changes are needed to the image path in your PR

2021-11-05 00:56 UTC, andrew-glenn approved these changes

2021-11-05 15:21 UTC, tonynv commented
Please resolve conflicts

2021-11-05 15:23 UTC, tonynv approved these changes

2021-11-05 15:23 UTC, GlennChia commented
Thanks @andrew-glenn for resolving the conflicts!

2021-11-05 15:25 UTC, andrew-glenn approved these changes

2021-11-05 15:25 UTC, merged