fixing issue with dockerfile
aws-ia/taskcat pull request #748
Opened 2022-07-20 18:08 UTC by troy-ameigh

## Overview

Brief description of what this PR does, and why it is needed (use case)?

## Testing/Steps taken to ensure quality

How did you validate the changes in this PR?

### Notes

Optional. Caveats, Alternatives, Other relevant information.

## Testing Instructions

 How to test this PR Start after checking out this branch (bulleted)
 * Include test case, and expected output

2022-07-20 18:10 UTC, tonynv commented
Is go and bash needed ?

2022-07-20 21:10 UTC, troy-ameigh commented
> Is go and bash needed ?

I added them as a fix for issue 747

2022-07-20 21:13 UTC, andrew-glenn submitted a review, later dismissed

2022-07-21 21:05 UTC, tlindsay42 approved these changes

2022-07-26 16:26 UTC, tonynv approved these changes

2022-07-26 16:30 UTC, andrew-glenn requested changes
Please run `pre-commit`. Travis is failing due to issues pre-commit would've picked up.

2022-07-26 16:52 UTC, closed without merging